---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bioconductor-biostrings=2.74.0
  - bioconductor-rtracklayer=1.66.0
  - conda-forge::r-tidyverse=2.0.0
  - bioconda::bioconductor-annotationdbi=1.68.0
  - bioconda::bioconductor-org.hs.eg.db=3.20.0
  - conda-forge::r-igraph=2.1.4
  - conda-forge::r-httr=1.4.7
  - conda-forge::r-jsonlite=2.0.0
  - bioconda::bioconductor-clusterprofiler=4.14.0
  - conda-forge::r-matrix=1.7_4
