---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-tidyverse=2.0.0
  - bioconda::bioconductor-org.hs.eg.db=3.20.0
  - bioconda::bioconductor-clusterprofiler=4.14.0
