---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-tidyverse=2.0.0
  - bioconda::bioconductor-biostrings=2.74.0
